-- GA / dataLayer Auditor Supabase schema
-- Run this once in Supabase SQL Editor before deploying the app.

create table if not exists public.ga_audit_templates (
    template_id text primary key,
    template_name text not null,
    domain_name text default '',
    measurement_id text default '',
    container_id text default '',
    url_pattern text default '',
    active boolean default true,
    created_by text default '',
    created_at text default ''
);

create table if not exists public.ga_audit_template_rules (
    rule_id text primary key,
    template_id text not null references public.ga_audit_templates(template_id) on delete cascade,
    rule_scope text not null check (rule_scope in ('execution', 'event')),
    field_name text not null,
    rule_type text not null check (rule_type in ('exact', 'one_of', 'contains', 'regex', 'required', 'optional')),
    expected_values text default '',
    notes text default '',
    created_by text default '',
    created_at text default ''
);

create table if not exists public.ga_audit_logs (
    id bigint generated by default as identity primary key,
    date text not null,
    email_id text default '',
    url_checked text default '',
    pageview_trigger_found boolean default false,
    execution_custom_dimensions text default '',
    execution_dimensions jsonb default '{}'::jsonb,
    created_at timestamptz default now()
);

create index if not exists idx_ga_audit_templates_domain
    on public.ga_audit_templates(domain_name);

create index if not exists idx_ga_audit_template_rules_template
    on public.ga_audit_template_rules(template_id);

create index if not exists idx_ga_audit_logs_created_at
    on public.ga_audit_logs(created_at desc);

create table if not exists public.bulk_audit_jobs (
    job_id text primary key,
    domain_name text default '',
    status text default 'queued',
    total_count integer default 0,
    completed_count integer default 0,
    failed_count integer default 0,
    requested_by text default '',
    payload jsonb default '{}'::jsonb,
    error_message text default '',
    created_at timestamptz default now(),
    started_at timestamptz,
    completed_at timestamptz
);

create table if not exists public.bulk_audit_results (
    result_id text primary key,
    job_id text not null references public.bulk_audit_jobs(job_id) on delete cascade,
    template_id text default '',
    template_name text default '',
    sample_url text default '',
    audit_outcome text default '',
    implementation_status text default '',
    ga_present boolean default false,
    pageview_triggered boolean default false,
    pageview_source text default '',
    events_count integer default 0,
    events_fired text default '',
    measurement_id text default '',
    container_id text default '',
    comscore_present boolean default false,
    chartbeat_present boolean default false,
    issues text default '',
    result_json jsonb default '{}'::jsonb,
    created_at timestamptz default now()
);

create index if not exists idx_bulk_audit_jobs_created_at
    on public.bulk_audit_jobs(created_at desc);

create index if not exists idx_bulk_audit_results_job
    on public.bulk_audit_results(job_id);
